/** Every API path in one place. */
export const endpoints = {
  catalog: "/catalog",
  plans: "/plans",
  me: "/me",
  meConsents: "/me/consents",
  mePrivacy: "/me/privacy",
  meNotifications: "/me/notifications",
  meNotificationsRead: "/me/notifications/read",
  meDeletion: "/me/deletion-request",
  myProfiles: "/me/profiles",
  myProfile: (id: string) => `/me/profiles/${id}`,
  myProfileAction: (id: string, action: string) => `/me/profiles/${id}/${action}`,
  profile: (idOrSlug: string) => `/profiles/${idOrSlug}`,
  billingQuote: "/billing/quote",
  subscriptions: "/billing/subscriptions",
  subscription: (id: string, action: string) => `/billing/subscriptions/${id}/${action}`,
  searchSparring: "/search/sparring",
  searchProviders: "/search/providers",
  providerCounts: "/search/providers/counts",
  comparison: "/comparison",
  comparisonOptions: "/comparison/options",
  contactWhatsapp: "/contacts/whatsapp",
  reports: "/reports",
  teams: "/teams",
  team: (idOrSlug: string) => `/teams/${idOrSlug}`,
  myTeams: "/teams/mine",
  links: "/links",
  linksInbox: "/links/inbox",
  linkRespond: (id: string) => `/links/${id}/respond`,
  events: "/events",
  eventsFeatured: "/events/featured",
  eventsOpenings: "/events/openings",
  myEvents: "/events/mine",
  myRegistrations: "/events/registrations/mine",
  event: (idOrSlug: string) => `/events/${idOrSlug}`,
  eventSub: (id: string, sub: string) => `/events/${id}/${sub}`,
  admin: {
    resources: "/admin/resources",
    resource: (name: string) => `/admin/resources/${name}`,
    resourceItem: (name: string, id: string) => `/admin/resources/${name}/${id}`,
    matrix: "/admin/plans/matrix",
    planFeature: (planId: string, key: string) => `/admin/plans/${planId}/features/${key}`,
    reprice: (planId: string) => `/admin/plans/${planId}/reprice`,
    coupons: "/admin/coupons",
    coupon: (id: string) => `/admin/coupons/${id}`,
    quotePreview: "/admin/billing/quote-preview",
    settings: "/admin/settings",
    setting: (key: string) => `/admin/settings/${key}`,
    subscriptions: "/admin/subscriptions",
    subscription: (id: string) => `/admin/subscriptions/${id}`,
    markPaid: (id: string) => `/admin/subscriptions/${id}/mark-paid`,
    users: "/admin/users",
    userBilling: (id: string) => `/admin/users/${id}/billing`,
    moderationProfiles: "/admin/moderation/profiles",
    moderationEvents: "/admin/moderation/events",
    verifications: "/admin/verifications",
    reports: "/admin/reports",
    metrics: "/admin/metrics",
    audit: "/admin/audit-logs",
  },
} as const;
